BnsManager/BnsManager/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFEntity;
using EFBusiness;

namespace BnsManager.Controllers
{
    public class OfferController : Controller
    {
        OfferBLL objOffer = new OfferBLL();
        OfferMapBLL objOfferMap = new OfferMapBLL();
        //
        // GET: /Offer/

        public ActionResult Index()
        {
            return View();
        }

        //GET: offer/create
        public ActionResult Create()
        {
            return View();
        }
        //POST: offer/create
        [HttpPost]
        public ActionResult Create(tblOffers Offer)
        {
            if (ModelState.IsValid)
            {
                Offer.RequestID = (int)Session["RequestID"];
                Offer.EmployeeID = 1;  //set defaut, continues
                objOffer.Insert(Offer);
            }
            return View(Offer);
        }

        [ChildActionOnly]
        public ActionResult OfferByCustomer()
        {
            int id = (int)Session["CustomerID"];
            var offers = objOfferMap.ListOfferByCustomer(id);
            return PartialView("OfferByCustomer", offers);
        }
        public ActionResult Details(int id)
        {
            var offer = objOfferMap.GetOfferByID(id);
            return View(offer);
        }
    }
}

BnsManager/BnsManager/Controllers/OverviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFEntity;
using EFBusiness;

namespace BnsManager.Controllers
{
    [Authorize(Roles = "Admin, Operator, Sales, Accounting")]
    public class OverviewController : Controller
    {
        //
        // GET: /Overview/
        OverviewBLL objOverview = new OverviewBLL();
        public ActionResult Index()
        {
            var overview = objOverview.ListAll();
            return View(overview);
        }

    }
}

BnsManager/BnsManager/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFEntity;
using EFBusiness;
namespace BnsManager.Controllers
{
    public class RequestController : Controller
    {
        RequestBLL objRequest = new RequestBLL();
        ProductBLL objProduct = new ProductBLL();
        RequestMapBLL objRequestMap = new RequestMapBLL();
        //
        // GET: /Order/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            if (Session["CustomerID"] != null)
            {
                ViewBag.Product = new SelectList(objProduct.ListProductAll(), "ID", "ProductName");
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Customer");
            }
        }

        [HttpPost]
        public ActionResult Create(tblRequests Request)
        {
            if (ModelState.IsValid)
            {
                Request.CustomerID = int.Parse(Session["CustomerID"].ToString());
                objRequest.Insert(Request);
                return RedirectToAction("Index", "Customer");
            }
            ViewBag.Product = new SelectList(objProduct.ListProductAll(), "ID", "ProductName");
            return View(Request);
        }

        [ChildActionOnly]
        public ActionResult RequestByCustomer()
        {
            //var request = objRequestMap.AllRequest();
            var request = objRequestMap.GetRequestByID(2);

            return PartialView("RequestByCustomer", request);
        }

        public ActionResult Details(int ID)
        {
            var request = objRequestMap.GetRequestByID(ID);
            Session["RequestID"] = request.ID;
            return View(request);
        }

        
    }
}

BnsManager/BnsManager/Views/Overview/Index.cshtml
@model IEnumerable<EFEntity.tblOverviews>
@using EFEntity
@{
    ViewBag.Title = "Overview";
    Layout = "~/Views/Shared/_LayoutPage_Sales.cshtml";
    <link href="~/Content/assets/data-tables/DT_bootstrap.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Content/assets/uniform/jquery.uniform.min.js"></script>
   <script type="text/javascript" src="~/Content/assets/data-tables/jquery.dataTables.js"></script>
   <script type="text/javascript" src="~/Content/assets/data-tables/DT_bootstrap.js"></script>
   
    <script src="~/Scripts/js/editable-table.js"></script>

   <!-- END JAVASCRIPTS -->
   <script>
       jQuery(document).ready(function() {
           EditableTable.init();
       });
   </script>
}
<!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <!-- BEGIN THEME CUSTOMIZER-->
                   <div id="theme-change" class="hidden-phone">
                       <i class="icon-cogs"></i>
                        <span class="settings">
                            <span class="text">Theme Color:</span>
                            <span class="colors">
                                <span class="color-default" data-style="default"></span>
                                <span class="color-green" data-style="green"></span>
                                <span class="color-gray" data-style="gray"></span>
                                <span class="color-purple" data-style="purple"></span>
                                <span class="color-red" data-style="red"></span>
                            </span>
                        </span>
                   </div>
                   <!-- END THEME CUSTOMIZER-->
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     Overview
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="#">Overview</a>
                           <span class="divider">/</span>
                       </li>
                       
                       <li class="active">
                           All 
                       </li>
                       <li class="pull-right search-wrap">
                           <form action="search_result.html" class="hidden-phone">
                               <div class="input-append search-input-area">
                                   <input class="" id="appendedInputButton" type="text">
                                   <button class="btn" type="button"><i class="icon-search"></i> </button>
                               </div>
                           </form>
                       </li>
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
<!-- END PAGE HEADER-->
<!-- BEGIN EDITABLE TABLE widget-->
             <div class="row-fluid">
                 <div class="span12">
                     <!-- BEGIN EXAMPLE TABLE widget-->
                     <div class="widget purple">
                         <div class="widget-title">
                             <h4><i class="icon-reorder"></i> All Customer </h4>
                            <span class="tools">
                                <a href="javascript:;" class="icon-chevron-down"></a>
                                <a href="javascript:;" class="icon-remove"></a>
                            </span>
                         </div>
                         <div class="widget-body">
                             <div>
                                 <div class="clearfix">
                                     
                                     <div class="btn-group pull-right">
                                         <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                                         </button>
                                         <ul class="dropdown-menu pull-right">
                                             <li><a href="#">Print</a></li>
                                             <li><a href="#">Save as PDF</a></li>
                                             <li><a href="#">Export to Excel</a></li>
                                         </ul>
                                     </div>
                                 </div>
                                 <div class="space15"></div>
                                 <table class="table table-striped table-hover table-bordered" id="editable-sample">
                                     <thead>
                                        <tr>
                                            
                                            <th> Request </th>
                                            <th> Offer </th>
                                            <th> Order </th>
                                            <th> Contract </th>
                                            <th> Invoice </th>
                                            
                                            <th> Booking </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var c in Model)
                                        { 
                                         <tr class="gradeA">
                                            
                                          
                                            <td> @Html.ActionLink(c.RequestID, "Details", "Request", new {id = c.Requestid} , null ) </td>
                                            <td> @if (c.Offerid == null || c.OfferID == null)
                                                 { 
                                                     @c.OfferID
                                                    
                                                 }
                                                 else
                                                 {
                                                    @Html.ActionLink(c.OfferID, "Details", "Offer", new {id = c.Offerid}, null )
                                                 }
                                            </td>
                                            <td class="center">
                                                @if (c.Orderid == null || c.OrderID == null)
                                                 { 
                                                     @c.OrderID
                                                    
                                                 }
                                                 else
                                                 {
                                                    @Html.ActionLink(c.OrderID, "Details", "Offer", new {id = c.Orderid}, null )
                                                 }

                                            </td>
                                            <td class="center"> 
                                                @if (c.Contractid == null || c.ContractID == null)
                                                 { 
                                                     @c.ContractID
                                                    
                                                 }
                                                 else
                                                 {
                                                    @Html.ActionLink(c.ContractID, "Details", "Offer", new {id = c.Contractid}, null )
                                                 }
                                            </td>
                                             <td> 
                                                 @if (c.Invoiceid == null || c.InvoiceID == null)
                                                 { 
                                                     @c.InvoiceID
                                                    
                                                 }
                                                 else
                                                 {
                                                    @Html.ActionLink(c.InvoiceID, "Details", "Offer", new {id = c.Invoiceid}, null )
                                                 }
                                             </td>
                                             <td>
                                                 @if (c.Bookingid == null || c.BookingID == null)
                                                 { 
                                                     @c.BookingID
                                                    
                                                 }
                                                 else
                                                 {
                                                    @Html.ActionLink(c.BookingID, "Details", "Offer", new {id = c.Bookingid}, null )
                                                 }
                                             </td>

                                        </tr>
                                        }
                                       
                                        
                                    </tbody>
                                 </table>
                             </div>
                         </div>
                     </div>
                     <!-- END EXAMPLE TABLE widget-->
                 </div>
             </div>

            <!-- END EDITABLE TABLE widget-->