BnsManager/BnsManager/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFBusiness;
using EFEntity;
namespace BnsManager.Controllers
{
    public class CustomerController : Controller
    {
        CustomerBLL objCustomer = new CustomerBLL();
        //
        // GET: /Customer/
        public ActionResult Index()
        {
            var customer = objCustomer.ListCustomerALl().ToList();
            return View(customer);
        }
        // GET: /Customer/Create
        public ActionResult Create()
        {
            return View();
        }
        //POST: /customer/create
        [HttpPost]
        public ActionResult Create(tblCustomers Customer)
        {
            if (ModelState.IsValid)
            {
                objCustomer.Insert(Customer);
                return RedirectToAction("Index", "Customer");
            }
            return View(Customer);
        }
        //GET: /customer/delete
        public ActionResult Delete(int ID)
        {
            objCustomer.Delete(ID);
            return RedirectToAction("Index", "Customer");
        }
        //GET: customer/edit
        public ActionResult Edit(int ID)
        {
            tblCustomers customer = objCustomer.GetCustomerByID(ID);
            return View(customer);
        }
        // POST : customer/edit
        [HttpPost]
        public ActionResult Edit(tblCustomers customer)
        {
            if (ModelState.IsValid)
            {
                objCustomer.Update(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }
        public ActionResult Details(int ID)
        {
            tblCustomers customer = objCustomer.GetCustomerByID(ID);
            Session["CustomerID"] = customer.ID;
            var a = Session["CustomerID"];
            return View(customer);
        }
    }
}

BnsManager/BnsManager/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFEntity;
using EFBusiness;

namespace BnsManager.Controllers
{
    public class OfferController : Controller
    {
        OfferBLL objOffer = new OfferBLL();
        OfferMapBLL objOfferMap = new OfferMapBLL();
        //
        // GET: /Offer/

        public ActionResult Index()
        {
            return View();
        }

        //GET: offer/create
        public ActionResult Create()
        {
            return View();
        }
        //POST: offer/create
        [HttpPost]
        public ActionResult Create(tblOffers Offer)
        {
            if (ModelState.IsValid)
            {
                Offer.RequestID = (int)Session["RequestID"];
                Offer.EmployeeID = 1;  //set defaut, continues
                objOffer.Insert(Offer);
            }
            return View(Offer);
        }

        [ChildActionOnly]
        public ActionResult OfferByCustomer()
        {
            int id = (int)Session["CustomerID"];
            var offers = objOfferMap.ListOfferByCustomer(id);
            return PartialView("OfferByCustomer", offers);
        }
        public ActionResult Details(int id)
        {
            var offer = objOfferMap.GetOfferByID(id);
            return View(offer);
        }
    }
}

BnsManager/BnsManager/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EFEntity;
using EFBusiness;

namespace BnsManager.Controllers
{
    public class OrderController : Controller
    {
        OrderBLL objOrder = new OrderBLL();
        OrderMapBLL objOrderMap = new OrderMapBLL();
        //
        // GET: /Order/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblOrders Order)
        {
            if (ModelState.IsValid)
            {
                Order.EmployeeID = 1; // default
                Order.RequestID = (int)Session["RequestID"];

                objOrder.Insert(Order);

            }
            return View(Order);
        }

        [ChildActionOnly]
        public ActionResult OrderByCustomer()
        {
            int id = (int)Session["CustomerID"];
            var order = objOrderMap.ListOrderByCustomer(id);
            return PartialView("OrderByCustomer", order);
        }

        public ActionResult Details(int id)
        {
            var order = objOrderMap.OrderByID(id);
            return View(order);
        }


    }
}

BnsManager/BnsManager/Views/Customer/Create.cshtml
@model EFEntity.tblCustomers
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage_Sales.cshtml";
}
@using(Html.BeginForm())
{
    @Html.ValidationSummary(true)
            <div class="row">
                <div class="col-lg-12 col-md-12 bns_form_head">
                    <p class="strong"> <strong> Customer / New </strong></p>
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                    @Html.ActionLink("Discard", "Index", "Customer", new {@class="btn btn-warning btn-sm" })
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			<div class="container-fluid">
                <div class="form-create">
                    <div class="form-header">
                        <div class="form-title">
                            <p>  Name (<input type="checkbox"> Is a Company? ) </p>
                            <div class="form-group">
                                <strong> Name: </strong>
                                @Html.TextBoxFor(model => model.Name, new {@class="form-control", @placeholder="Name" })
                            </div>
                            <div class="form-group">
                                <strong> CustomerID: </strong>
                                @Html.TextBoxFor(model => model.CustomerID, new {@class="form-control", @placeholder="Customer ID" })
                            </div>
                        </div>
                        <div class="form-option">
                            <ul> 
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>

                            </ul>
                        </div>

                    </div>


                    <div class="form-content">
                            <table class="table">
                            <tbody>
                                <tr>     
                                    <td> <strong> Address </strong>   </td>
                                    <td> @Html.TextBoxFor(model => model.Address1, new {@class="form-control", @placeholder="Address..." })</td>
                                    <td> <strong> Phone </strong>  </td>
                                    <td>  @Html.TextBoxFor(model => model.Phone1, new {@class="form-control", @placeholder="01662115090" }) </td>
                                </tr>

                                <tr>     
                                    <td> <strong> City </strong>   </td>
                                    <td>  @Html.TextBoxFor(model => model.Address2, new {@class="form-control", @placeholder="City..." }) </td>
                                    <td> <strong> Mobile </strong>  </td>
                                    <td>  @Html.TextBoxFor(model => model.Phone2, new {@class="form-control", @placeholder="01662115090" }) </td>
                                </tr>

                                <tr>     
                                    <td>  <strong> Web site </strong>  </td>
                                    <td>  @Html.TextBoxFor(model => model.Website, new {@class="form-control", @placeholder="bnstravel.com" }) </td>
                                    <td> <strong> Email </strong>  </td>
                                    <td>  @Html.TextBoxFor(model => model.Email, new {@class="form-control", @placeholder="tiendao.online@gmail.com" }) </td>
                                </tr>
                                
                                
                            </tbody>
                        </table>

                    </div>


                    <div class="form-footer">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                         
                          <li><a href="#internalNote" role="tab" data-toggle="tab">Internal Notes</a></li>
                          <li><a href="#salePurchase" role="tab" data-toggle="tab"> Sales &amp; Purchase</a></li>
                          <li><a href="#accounting" role="tab" data-toggle="tab"> Accounting </a></li>
                          <li><a href="#pointSale" role="tab" data-toggle="tab"> Point of Sale </a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                          <div class="tab-pane" id="internalNote"> 
                            @Html.TextAreaFor(model => model.Notes, new {@class="form-control", @placeholder="Put an interal notes..." })
                          </div>
                          <div class="tab-pane" id="salePurchase"> salePurchase </div>
                          <div class="tab-pane" id="accounting">  accounting </div>
                          <div class="tab-pane" id="pointSale">  pointSale </div>
                        </div>


                    </div>

                </div>
                
               
            </div>
            <!-- /.container-fluid -->
            <!-- /.row -->
			
}
            
			
			

BnsManager/BnsManager/Views/Customer/Details.cshtml
@model EFEntity.tblCustomers
@{
    ViewBag.Title = "Details";
}

<div class="row">
                <div class="col-lg-12 col-md-12 bns_form_head">
                    <p class="strong"> <strong> Customer / New </strong></p>
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                    @Html.ActionLink("Discard", "Index", "Customer", new {@class="btn btn-warning btn-sm" })
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			<div class="container-fluid">
                <div class="form-create">
                    <div class="form-header">
                        <div class="form-title">
                            <p>  Name (<input type="checkbox"> Is a Company? ) </p>
                            <div class="form-group">
                                <strong> Name: </strong>
                                @Model.Name
                            </div>
                            <div class="form-group">
                                <strong> CustomerID: </strong>
                                @Model.CustomerID
                            </div>
                        </div>
                        <div class="form-option">
                            <ul> 
                                
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> @Html.ActionLink("Request", "Create", "Request", null , new {@class="btn btn-warning btn-sm" }) </li>

                            </ul>
                        </div>

                    </div>


                    <div class="form-content">
                            <table class="table">
                            <tbody>
                                <tr>     
                                    <td> <strong> Address </strong>   </td>
                                    <td> @Model.Address1 </td>
                                    <td> <strong> Phone </strong>  </td>
                                    <td>  @Model.Phone1</td>
                                </tr>

                                <tr>     
                                    <td> <strong> City </strong>   </td>
                                    <td> @Model.Address2</td>
                                    <td> <strong> Mobile </strong>  </td>
                                    <td>  @Model.Phone2  </td>
                                </tr>

                                <tr>     
                                    <td>  <strong> Web site </strong>  </td>
                                    <td> @Model.Website </td>
                                    <td> <strong> Email </strong>  </td>
                                    <td> @Model.Email </td>
                                </tr>
                                
                                
                            </tbody>
                        </table>

                    </div>


                    <div class="form-footer">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                         
                          <li><a href="#internalNote" role="tab" data-toggle="tab">Internal Notes</a></li>
                          <li><a href="#salePurchase" role="tab" data-toggle="tab"> Order </a></li>
                          <li><a href="#accounting" role="tab" data-toggle="tab"> Offer </a></li>
                          <li><a href="#pointSale" role="tab" data-toggle="tab"> Request </a></li>
                          

                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                          <div class="tab-pane" id="internalNote"> 
                            @Model.Notes
                          </div>
                          <div class="tab-pane" id="salePurchase"> 
                              @Html.Action("OrderByCustomer","Order")

                          </div>
                          <div class="tab-pane" id="accounting">  
                              @Html.Action("OfferByCustomer", "Offer")
                             
                          </div>
                          <div class="tab-pane" id="pointSale">  

                              @Html.Action("RequestByCustomer","Request")
                          </div

                         
                            
                        </div>


                    </div>

                </div>
                
               
            </div>
            <!-- /.container-fluid -->
            <!-- /.row -->
			

BnsManager/BnsManager/Views/Customer/Edit.cshtml
@model EFEntity.tblCustomers
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage_Sales.cshtml";
}
@using(Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ID)
            <div class="row">
                <div class="col-lg-12 col-md-12 bns_form_head">
                    <p class="strong"> <strong> Customer / New </strong></p>
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                    @Html.ActionLink("Discard", "Index", "Customer", new {@class="btn btn-warning btn-sm" })
                </div>
                <!-- /.col-lg-12 -->
            </div>
			
			<div class="container-fluid">
                <div class="form-create">
                    <div class="form-header">
                        <div class="form-title">
                            <p>  Name (<input type="checkbox"> Is a Company? ) </p>
                            <div class="form-group">
                                <strong> Name: </strong>
                                @Html.TextBoxFor(model => model.Name, new {@class="form-control", @placeholder="Name" })
                            </div>
                            <div class="form-group">
                                <strong> Customer ID: </strong>
                                @Html.TextBoxFor(model => model.CustomerID, new {@class="form-control", @placeholder="Customer ID" })
                            </div>
                        </div>
                        <div class="form-option">
                            <ul> 
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>
                                <li> <button type="button" class="btn btn-default btn-sm"> Opportunities </button> </li>

                            </ul>
                        </div>

                    </div>


                    <div class="form-content">
                            <table class="table">
                            <tbody>
                                <tr>     
                                    <td>  <strong> Address </strong>  </td>
                                    <td> @Html.TextBoxFor(model => model.Address1, new {@class="form-control", @placeholder="Address..." })</td>
                                    <td> <strong> Phone </strong> </td>
                                    <td>  @Html.TextBoxFor(model => model.Phone1, new {@class="form-control", @placeholder="01662115090" }) </td>
                                </tr>

                                <tr>     
                                    <td>  <strong> City </strong>  </td>
                                    <td>  @Html.TextBoxFor(model => model.Address2, new {@class="form-control", @placeholder="City..." }) </td>
                                    <td> <strong> Mobile </strong> </td>
                                    <td>  @Html.TextBoxFor(model => model.Phone2, new {@class="form-control", @placeholder="01662115090" }) </td>
                                </tr>

                                <tr>     
                                    <td>  <strong> Web Site </strong> </td>
                                    <td>  @Html.TextBoxFor(model => model.Website, new {@class="form-control", @placeholder="bnstravel.com" }) </td>
                                    <td> <strong> Email </strong> </td>
                                    <td>  @Html.TextBoxFor(model => model.Email, new {@class="form-control", @placeholder="tiendao.online@gmail.com" }) </td>
                                </tr>
                                
                                
                            </tbody>
                        </table>

                    </div>


                    <div class="form-footer">
                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                         
                          <li><a href="#internalNote" role="tab" data-toggle="tab">Internal Notes</a></li>
                          <li><a href="#salePurchase" role="tab" data-toggle="tab"> Sales &amp; Purchase</a></li>
                          <li><a href="#accounting" role="tab" data-toggle="tab"> Accounting </a></li>
                          <li><a href="#pointSale" role="tab" data-toggle="tab"> Point of Sale </a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">
                          <div class="tab-pane" id="internalNote"> 
                            @Html.TextAreaFor(model => model.Notes, new {@class="form-control", @placeholder="Put an interal notes..." })
                          </div>
                          <div class="tab-pane" id="salePurchase"> salePurchase </div>
                          <div class="tab-pane" id="accounting">  accounting </div>
                          <div class="tab-pane" id="pointSale">  pointSale </div>
                        </div>


                    </div>

                </div>
                
               
            </div>
            <!-- /.container-fluid -->
            <!-- /.row -->
			
}
            
			
			

BnsManager/BnsManager/Views/Customer/Index.cshtml
@model IEnumerable<EFEntity.tblCustomers>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage_Sales.cshtml";
    <link href="~/Content/css/plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/Scripts/js/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        $('#dataTables-example').dataTable();
    });
    </script>
   
}
            <div class="row">
               <div class="col-lg-12 col-md-12 bns_form_head">
                    <p class="strong"> <strong> Customer</strong></p>
                    <div> 
                        @Html.ActionLink("Create", "Create", "Customer", new {@class = "btn btn-primary btn-sm active"})
                    </div>
                    
                    
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            DataTables Advanced Tables
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th> Customer Name </th>
                                            <th> Address </th>
                                            <th> Email </th>
                                            <th> Phone </th>
                                            <th> Website </th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var c in Model)
                                        { 
                                         <tr class="gradeA">
                                            <td> @c.Name </td>
                                            <td> @c.Address1</td>
                                            <td> @c.Email</td>
                                            <td class="center"> @c.Phone1</td>
                                            <td class="center"> @c.Website </td>
                                             <td> @Html.ActionLink("Edit", "Edit", new { ID = @c.ID }) 
                                                 @Html.ActionLink("Delete", "Delete", new { ID = @c.ID }, new { @onclick = "return confirm('Are you sure you wish to delete this article?');" })
                                                 @Html.ActionLink("Details", "Details", new {ID = @c.ID })

                                             </td>

                                        </tr>
                                        }
                                       
                                        
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            